name: CI

#main ブランチへの push/PR トリガー
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            #コードをチェックアウト
            - uses: actions/checkout@v3

            #Node.jsのセットアップ
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16'
            
            #Pythonのセットアップ
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'

            #Node 依存関係のインストール
            - name: Install Node dependencies
              run: |
                cd react-todo-app
                npm install

            #Python 依存関係のインストール
            - name: Install Python dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            #Playwright ブラウザのインストール
            - name: Install Playwright browsers
              run: |
                python -m playwright install

            #React アプリをバックグラウンドで起動し、起動完了を待機
            - name: Start React app
              run: |
                cd react-todo-app
                npm start &
                cd ..
                #サーバー立ち上げまで待機
                for i in {1..15}; do
                    if curl -s http://localhost:3000 >/dev/null; then
                        echo "Server is up"
                        break
                    else
                        echo "Waiting for server..."
                        sleep 2
                    fi
                done
            
            #pytest によるテスト実行(HTMLレポート付き)
            - name: Run tests
              run: |
                pytest --html=report.html --self-contained-html
            
            #生成されたレポートをアーティファクトとしてアップロード
            - name: Upload report
              uses: actions/upload-artifact@v4.6.2
              with:
                name: pytest-report
                path: report.html
